namespace OrpheusInterfaces.Interfaces.Attributes
{
    /// <summary>
    /// Orpheus primary key attribute
    /// </summary>
    public interface IPrimaryKey : IOrpheusBaseAttribute
    {
        /// <summary>
        /// Indicates if the primary key value is auto-generated.
        /// </summary>
        /// <returns>True if the key is generated from the DB engine</returns>
        bool IsDBGenerated { get; }

        /// <summary>
        /// Indicates if the primary key value will be auto-generated in memory.
        /// Only System.Guid type is supported.
        /// </summary>
        /// <returns>True if the key value is auto-generated.</returns>
        bool IsAutoGenerated { get;  }
    }
}
