using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OrpheusAttributes
{
    /// <summary>
    /// Primary key constraint attribute.
    /// Decorate a property with attribute to create a primary key constraint on a schema object.
    /// </summary>
    public class PrimaryKey : OrpheusBaseAttribute
    {
        /// <summary>
        /// Indicates if the primary key value is auto-generated.
        /// </summary>
        /// <returns>True if the key is generated from the DB engine</returns>
        public bool IsDBGenerated { get; private set; }

        /// <summary>
        /// Indicates if the primary key value will be auto-generated in memory.
        /// Only System.Guid type is supported.
        /// </summary>
        /// <returns>True if the key value is auto-generated.</returns>
        public bool IsAutoGenerated { get; private set; }

        /// <summary>
        /// Primary key attribute constructor.
        /// </summary>
        /// <param name="isDBGenerated">True if the key is generated from the DB engine</param>
        /// <param name="isAutoGenerated">True if the key value is auto-generated</param>
        public PrimaryKey(bool isAutoGenerated = true,bool isDBGenerated = false)
        {
            this.IsDBGenerated = isDBGenerated;
            this.IsAutoGenerated = isAutoGenerated;
        }
    }
}
