using OrpheusInterfaces.Interfaces.Attributes;

namespace OrpheusAttributes
{
    /// <summary>
    /// Primary key constraint attribute.
    /// Decorate a property with attribute to create a primary key constraint on a schema object.
    /// </summary>
    public class PrimaryKey : OrpheusBaseAttribute, IPrimaryKey
    {
        /// <value>
        /// Indicates if the primary key value is auto-generated.
        /// </value>
        public bool IsDBGenerated { get; private set; }

        /// <value>
        /// Indicates if the primary key value will be auto-generated in memory.
        /// Only System.Guid type is supported.
        /// </value>
        public bool IsAutoGenerated { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="PrimaryKey"/> class.
        /// </summary>
        /// <param name="isAutoGenerated">if set to <c>true</c> [is automatic generated].</param>
        /// <param name="isDBGenerated">if set to <c>true</c> [is database generated].</param>
        public PrimaryKey(bool isAutoGenerated = true,bool isDBGenerated = false)
        {
            this.IsDBGenerated = isDBGenerated;
            this.IsAutoGenerated = isAutoGenerated;
        }
    }
}
